name: Build Edge image and push to DockerHub

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish Docker image
    if: ${{ github.ref == 'refs/heads/palm-migration' }}
    runs-on: ubuntu-latest

    outputs:
      release_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0

        with:
          github_token: ${{ secrets.RELEASES_ACTION_GITHUB_TOKEN }}
          tag_prefix: ""
          fetch_all_tags: true
          release_branches: "main,develop,palm-migration"


      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          push: true
          file: Dockerfile.mainnet
          tags: |
            gatewayfm/polygon-edge:mainnet-latest
            gatewayfm/polygon-edge:mainnet-${{ steps.tag_version.outputs.new_tag }}

      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          push: true
          file: Dockerfile.testnet
          tags: |
            gatewayfm/polygon-edge:testnet-latest
            gatewayfm/polygon-edge:testnet-${{ steps.tag_version.outputs.new_tag }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.RELEASES_ACTION_GITHUB_TOKEN }}
